export const detectRobot = (userAgent: string): boolean => {
	const robots = new RegExp(
		(
			[
				/bot/i,
				/crawl(er|ing)?/i,
				/spider/i,
				/slurp/i,
				/search/i,
				/bingbot/i,
				/googlebot/i,
				/yandexbot/i,
				/duckduckbot/i,
				/baiduspider/i,
				/facebookexternalhit/i,
				/twitterbot/i,
				/linkedinbot/i,
				/msnbot/i,
				/applebot/i,
				/pingdom/i,
				/ahrefsbot/i,
				/mj12bot/i,
				/semrushbot/i,
				/rogerbot/i,
				/exabot/i,
				/dotbot/i,
				/ia_archiver/i,
				/gigabot/i,
				/turnitinbot/i,
				/yahoobot/i,
				/ezooms/i,
				/radian6/i,
				/archive\.org_bot/i,
				/uptimerobot/i,
				/adsbot-google/i,
				/mediapartners-google/i,
				/adsbot-google-mobile(-apps)?/i,
				/googlebot-(image|news|video)/i,
				/bot/i,
				/crawl(er|ing)?/i,
				/spider/i,
				/slurp/i,
				/search/i,
				/bingbot/i,
				/googlebot/i,
				/yandexbot/i,
				/duckduckbot/i,
				/baiduspider/i,
				/facebookexternalhit/i,
				/twitterbot/i,
				/linkedinbot/i,
				/msnbot/i,
				/applebot/i,
				/pingdom/i,
				/ahrefsbot/i,
				/mj12bot/i,
				/semrushbot/i,
				/rogerbot/i,
				/exabot/i,
				/dotbot/i,
				/ia_archiver/i,
				/gigabot/i,
				/turnitinbot/i,
				/yahoobot/i,
				/ezooms/i,
				/radian6/i,
				/archive\.org_bot/i,
				/uptimerobot/i,
				/adsbot-google/i,
				/mediapartners-google/i,
				/adsbot-google-mobile(-apps)?/i,
				/googlebot-(image|news|video)/i,
				/google web preview/i,
				/google-structured-data-testing-tool/i,
				/google page speed/i,
				/google keyword/i,
				/google search console/i,
				/googlebot-image/i,
				/googlebot-news/i,
				/googlebot-video/i,
				/google-ads/i,
				/googlebot-mobile/i,
				/google favicon/i,
				/google-web-light/i,
				/google-speakr/i,
				/googleplus/i,
				/google wireless/i,
				/google wireless transcoder/i,
				/google translate/i,
				/google-site-verification/i,
				/google-play/i,
				/google-proxy/i,
				/google-publisher/i,
				/google-ping/i,
				/google-pigeon/i,
				/google-one-tap/i,
				/google-my-business/i,
				/google-browsing/i,
				/google-analytics/i,
				/google-adwords/i,
				/feedfetcher-google/i,
				/adsbot-google-mobile(-apps)?/i,
				/google-translate/i,
				/google-publisher/i,
				/google-maps/i,
				/google-image-proxy/i,
				/google-feedfetcher(-i18n)?/i,
				/google-feedback/i,
				/google-eclipse/i,
				/google-deskbar/i,
				/google-cloud/i,
				/google-inspectiontool/i,
			] as RegExp[]
		)
			.map((r) => r.source)
			.join("|"),
		"i",
	);

	return robots.test(userAgent);
};
